export declare const V1: URL;
export declare const paths: {
    artworks: string;
    agents: string;
    places: string;
    galleries: string;
    exhibitions: string;
    products: string;
    texts: string;
    sounds: string;
    images: string;
    videos: string;
    tours: string;
    sections: string;
    sites: string;
    publications: string;
    events: string;
    articles: string;
    highlights: string;
    'artwork-types': string;
    'artwork-date-qualifiers': string;
    'artwork-place-qualifiers': string;
    'agent-roles': string;
    'agent-types': string;
    'category-terms': string;
    'mobile-sounds': string;
    'event-occurrences': string;
    'event-programs': string;
    'static-pages': string;
    'generic-pages': string;
    'press-releases': string;
    'educator-resources': string;
    'digital-catalogs': string;
    'digital-publication-sections': string;
    'printed-catalogs': string;
};
